name: React Frontend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd task-manager-frontend
          npm install

      - name: Build React App
        env:
          REACT_APP_API_URL: https://task-manager-j13m.onrender.com/api/
        run: |
          cd task-manager-frontend
          npm run build